name: Discord Rich Presence Activity Badge

on:
  schedule:                 # Scheduling with Github Actions is inconsistent
    - cron: "5 0-23 * * *"  # Construct your Cronjob Schedule at https://crontab.guru/

  workflow_dispatch:        # Enables you to dispatch the workflow at your click

jobs:
  BadgeUpdater:
    name: Static Badge Updater
    runs-on: ubuntu-latest

    steps:
      - name: Update README Discord Badge to Latest Upstream
        uses: CodexLink/discord-activity-badge@v1.0 # Choose your own version by picking a tag or a branch name. Using a tag is recommended.
        with: # Go to your Repository Secrets and fill those up!
          DISCORD_USER_ID: ${{ secrets.DEX_SECRET_1 }}
          DISCORD_BOT_TOKEN: ${{ secrets.DEX_SECRET_2 }}
